### ISSUE TITLE
UI: Musen borde ändra utseende när man hove'rar över dialogrutan.  

### ISSUE THREAD

**Issue by AlexanderBergkvist** [MarkusSagen/Surmize#46]
Idag förstod inte många att rutan är det som ska klickas på. Man gör det klassiska studentportalen misstaget och klickar på uppload för att få ladda upp filer

**Comment by AlexanderBergkvist** [comment]
Alt metoder att visa att sidan är klickade går ju också bra, men tyckte det var ett bra förslag.

**Comment by MarkusSagen** [comment]
Done
